[build]
  command = "npm run build:netlify"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"
